---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=git://github.com/craigeebach/kaniko-demo",
            "--destination=craigeebach/devops-toolkit-vfarcic:1.0.0"]
  restartPolicy: Never

